//! Automatically generated by:
//!
//!    generate.py examples/nutshell/xml/index.xsd rust/src/doxygen/index/elements.rs
//!

#[derive(Debug, PartialEq)]
pub struct DoxygenType {
    // Attributes
    // pub version: String,
    // Elements
    pub compound: Vec<CompoundType>,
}

#[derive(Debug, PartialEq)]
pub struct CompoundType {
    // Attributes
    pub ref_id: String,
    pub kind: CompoundKind,
    // Elements
    pub name: String,
    pub member: Vec<MemberType>,
}

#[derive(Debug, PartialEq)]
pub struct MemberType {
    // Attributes
    pub ref_id: String,
    pub kind: MemberKind,
    // Elements
    pub name: String,
}

#[derive(Debug, strum::EnumString, PartialEq)]
#[strum(serialize_all = "kebab-case")]
pub enum CompoundKind {
    Class,
    Struct,
    Union,
    Interface,
    Protocol,
    Category,
    Exception,
    File,
    Namespace,
    Group,
    Page,
    Example,
    Dir,
    Type,
    Concept,
}

#[derive(Debug, strum::EnumString, PartialEq)]
#[strum(serialize_all = "kebab-case")]
pub enum MemberKind {
    Define,
    Property,
    Event,
    Variable,
    Typedef,
    Enum,
    Enumvalue,
    Function,
    Signal,
    Prototype,
    Friend,
    Dcop,
    Slot,
}
